import random,time

file=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
sample=""

def generate(file,sample,digits):
    while digits>0:
        digits-=1
        sample+=random.choice(file)
        continue
    open('//storage//emulated//0//passwords.txt','a').write(f'{str(sample)}\n')
    print(f'\033[1;32m"{sample}"','\n')

lebel='THIS FILE IS AUTOMATICALLY GENERATED BY A PYTHON SCRIPT'
times=int(input('\033[1;33mNumber of password ?(enter a small valid number) '))
print(f'\033[3mGenerating passwords...')
open('//storage//emulated//0//passwords.txt','a').write('')
f=open('//storage//emulated//0//passwords.txt','r')
if lebel not in f.read():
    print('\033[3mlebel is being regenerated')
    open('//storage//emulated//0//passwords.txt','a').write(f'{lebel}\n')
else:
    print('\033[3mlebel is found')

while times>0:
    times-=1   
    generate(file,sample,8)
    time.sleep(0.25)
    continue
else:
    print('\033[1;33msuccessfully generated!!!')
    print('\033[3mA text file has been generated containing all the passwords\n')
    exit()